### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by mickare** [Borlea/EchoPet#134]
Version: 1.0.4-SNAPSHOT-b13

> [20:27:40] [Server thread/WARN]: [EchoPet] Task #1856140 for EchoPet v1.0.4-SNAPSHOT-b13 generated an exception
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_92]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_92]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:92) ~[?:?]
	at com.dsh105.echopet.listeners.PetOwnerListener$1.run(PetOwnerListener.java:199) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-910]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-910]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-910]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]

**Comment by Borlea** [comment]
How about you update a little so the line numbers are relevant.

**Comment by mickare** [comment]
Yes, we will upgrade to a newer version if there are fewer players online.

I looked at the current code and found a clear suspect:
https://github.com/Borlea/EchoPet/blob/master/modules/EchoPet/src/com/dsh105/echopet/api/pet/Pet.java#L94
https://github.com/Borlea/EchoPet/blob/master/modules/EchoPet/src/com/dsh105/echopet/api/PetManager.java#L652

You could clone the petdata-array in the for loop (or create a new arraylist).
