### ISSUE TITLE
Mixing v1_8_R3 and v1_11_R1?

### ISSUE THREAD

**Issue by L4BORG** [Borlea/EchoPet#165]
https://github.com/Borlea/EchoPet/blob/master/modules/v1_8_R3/src/com/dsh105/echopet/compat/nms/v1_8_R3/entity/EntityPet.java#L46

```
[13:52:06] [Server thread/ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.NoClassDefFoundError: net/minecraft/server/v1_11_R1/EnumHand
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_111]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_111]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_111]
	at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:75) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:86) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:86) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:70) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.reflect.accessors.Accessors.getMethodAccessor(Accessors.java:243) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.utility.MinecraftReflection.getBukkitEntity(MinecraftReflection.java:358) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:238) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:982) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:693) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:678) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:146) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib.jar:3.6.5-b222]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.pre1_9.WrapperPlayServerSpawnEntityLiving.getEntity(WrapperPlayServerSpawnEntityLiving.java:70) ~[HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.pre1_9.WrapperPlayServerSpawnEntityLiving.getEntity(WrapperPlayServerSpawnEntityLiving.java:79) ~[HolographicDisplays.jar:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.pre1_9.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:71) ~[HolographicDisplays.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:318) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:401) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:82) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.handleScheduled(NettyChannelInjector.java:367) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.onMessageScheduled(NettyChannelInjector.java:335) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127) [ProtocolLib.jar:3.6.5-b222]
	at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95) [ProtocolLib.jar:3.6.5-b222]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:916) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:354) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:452) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:112) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:75) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.World.a(World.java:1072) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1003) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1065) [patched.jar:git-TacoSpigot-"65fd35f"]
	at com.dsh105.echopet.compat.nms.v1_8_R3.SpawnUtil.spawn(SpawnUtil.java:59) [EchoPet.jar:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:91) [EchoPet.jar:?]
	at com.dsh105.echopet.listeners.PetOwnerListener$2.run(PetOwnerListener.java:237) [EchoPet.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_11_R1.EnumHand
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
	... 52 more
```

**Comment by DrkMatr1984** [comment]
Looks like to me you're using a 1.11 version of protocollib or holographic displays. Make sure you're using the proper version for 1.8.3

**Comment by L4BORG** [comment]
Latest https://dev.bukkit.org/projects/holographic-displays/files/956385 (Compatibility: Bukkit/Spigot/Cauldron 1.7.x, 1.8.x, 1.9.x, 1.10.x, 1.11)

and ProtocolLib for 1.8:
```
>protocol version
[17:48:32 INFO]: ProtocolLib v3.6.5
[17:48:32 INFO]: Authors: dmulloy2 and Comphenix
[17:48:32 INFO]: Issues: https://github.com/dmulloy2/ProtocolLib/issues
```

Why was this even changed? Swapping the function with the one from old EchoPet NMS would fix the issue.

**Comment by Borlea** [comment]
It wasn't changed, it was copied from 1.9.

Just for some reason the 1.8 module had access  to 1.11 nms methods when it shouldn't and my ide auto imported it instead of giving errors.

Will be fixed later today

**Comment by L4BORG** [comment]
Fix confirmed.
