### ISSUE TITLE
InvalidPluginException

### ISSUE THREAD

**Issue by Mstrodl** [Borlea/EchoPet#19]
Sorry to be a bother, but when I compile it and put `target/EchoPet.jar` into my plugins folder, I get this error on startup:

>[17:01:29] [Server thread/ERROR]: Could not load 'plugins/EchoPet-1.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/dsh105/echopet/compat/api/plugin/IEchoPetPlugin
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [Spigot.jar:git-Spigot-6f291ea-6026dad]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [Spigot.jar:git-Spigot-6f291ea-6026dad]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [Spigot.jar:git-Spigot-6f291ea-6026dad]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [Spigot.jar:git-Spigot-6f291ea-6026dad]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.lang.NoClassDefFoundError: com/dsh105/echopet/compat/api/plugin/IEchoPetPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_73]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_73]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_73]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_73]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_73]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_73]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_73]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_73]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_73]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.dsh105.echopet.compat.api.plugin.IEchoPetPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_73]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_73]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_73]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_73]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_73]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_73]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_73]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_73]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_73]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_73]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[Spigot.jar:git-Spigot-6f291ea-6026dad]
	... 6 more

If @Borlea would like to see my Jenkins server, please tell me and we can arrange it (somehow...)

**Comment by Borlea** [comment]
You need to use EchoPet-Shaded.jar as it has all the modules included in it

**Comment by Mstrodl** [comment]
Oh, thanks. Those were the only ones I didn't try. Any chance there'll be built versions made?

**Comment by Borlea** [comment]
Once I understand jenkins and feel it's in a state I like.

**Comment by Mstrodl** [comment]
Oh, I have it working on my Jenkins server.

**Comment by Borlea** [comment]
I would prefer it to be built on my jenkins server but I just don't have full understanding of how to use it just yet.

**Comment by Mstrodl** [comment]
I installed a few plugins and was off to the races. If you'd like, I can take pictures of my plugins and their configs.

**Comment by Borlea** [comment]
Sure, would love any help I can get

**Comment by Mstrodl** [comment]
Ok, sounds good. I'll start taking pictures.

**Comment by Mstrodl** [comment]
[EchoPet Config [Jenkins].pdf](https://github.com/Borlea/EchoPet/files/170654/EchoPet.Config.Jenkins.pdf)

**Comment by Mstrodl** [comment]
For the EchoPet job, use the Maven template

**Comment by Mstrodl** [comment]
[Configure System [Jenkins].pdf](https://github.com/Borlea/EchoPet/files/170655/Configure.System.Jenkins.pdf)
[Manage Plugins [Jenkins].pdf](https://github.com/Borlea/EchoPet/files/170656/Update.Center.Jenkins.pdf)

**Comment by Mstrodl** [comment]
Also, you need to make sure you have a Bukkit jar. I have a job on my Jenkins that builds it for me and I have a pre-build step that adds the jar to Maven.

**Comment by Mstrodl** [comment]
You don't need all the plugins I have. Most of mine are for other things.

**Comment by Mstrodl** [comment]
Borlea!!!! Stop hijacking my jenkins!!!

**Comment by Mstrodl** [comment]
When I said 
> Oh, I have it working on my Jenkins server

I was trying to tell you how easy it was. It took me ~5 min of fiddling (once I figured out the maven-assembly-plugin thing)
