### ISSUE TITLE
Just reporting > Could not pass event PlayerTeleportEvent

### ISSUE THREAD

**Issue by random1167** [Borlea/EchoPet#91]
Just reporting an error
```
[08:30:01 ERROR]: Could not pass event PlayerTeleportEvent to EchoPet v1.0.2-SNAPSHOT-b
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.teleport(CraftPlayer.java:459) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:622) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
        at com.dsh105.echopet.api.pet.Pet.setAsHat(Pet.java:386) ~[?:?]
        at com.dsh105.echopet.listeners.PetOwnerListener.onPlayerTeleport(PetOwnerListener.java:120) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
        ... 16 more

```
nothing is breaking..i dont think, This just popped up in my console.
hope im on the correct echopet page XD

**Comment by Borlea** [comment]
From the first line of the exception no build version is displayed.. I'm unable to track down the possible issue.

I suggest updating to build 40.
